# Generated by Django 3.0.3 on 2020-03-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='ParteDelCuerpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Partes del cuerpo',
            },
        ),
        migrations.CreateModel(
            name='Demonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Ciudad', unique=True)),
                ('partedelcuerpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.ParteDelCuerpo', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Demonios',
            },
        ),
    ]
