# Generated by Django 3.0.3 on 2020-03-09 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Personajes',
            },
        ),
        migrations.CreateModel(
            name='ResultadoPelea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Resultados Peleas',
            },
        ),
        migrations.CreateModel(
            name='Pelea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Demonio')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Personaje')),
                ('resultadopelea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.ResultadoPelea')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.Personaje')),
            ],
            options={
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
